# Generated by Django 4.1.3 on 2022-12-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledata', '0003_passouts_delete_passout'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
