# Generated by Django 4.1.3 on 2022-12-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabledata', '0004_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='name',
            new_name='fee',
        ),
    ]
