# Generated by Django 4.1.3 on 2022-12-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledata', '0005_rename_name_fee_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='feetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('totalfee', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
